Capstone: motorcycle appointment app
Bennyjoez/motorcycle-appointment-app-front-end pull request #25
Opened 2023-09-05 18:05 UTC by Adams-Ghub

## The following were carried out in this project

- Create a register page to allow users to create an account with a unique username.
- Create a login page to allow users to login
- Create a navigation panel where the user can see all links to the following pages
    - Motorcycles
    - Reserve
    - My reservations
    - Add Motorcycles
    - Delete
 - Display all motorcycles on the Motorcycles/Home page
 - Display details of a selected motorcycle on the Details page with a button to the reserve form
 - Display form for adding a motorcycle with the related details.
 - Display form to reserve a motorcycle with the following features
    - User and Model are auto-filled if the button on the details page is clicked. 
    - User is auto-filled if the button on the navigation bar is clicked.
 - Display a list of all reservations that have been made in the Reservations page
 - Display a list of all motorcycles with title and Delete button to delete a motorcyle.
 - Made the project responsive using mobile-first approach
 
[backend pull request](https://github.com/Bennyjoez/motorcycle-appointment-app-backend/pull/19)

2023-09-05 19:06 UTC, Meltrust requested changes
Hi @Adams-Ghub,

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation, but you are almost there!






### To highlight:

-  Tests are passing✔️
-  Nice code organization ✔️ 
-  App is working well✔️ 
-  Good readme ✔️ 
-  Beautiful frontend ✔️ 



#### You are really close to finishing the Microverse program!! Keep it up! 👍👍👍

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

### After implementing the requested changes, please submit another review request. ♻️
_Check the comments under the review._







Cheers and Happy coding!👏👏👏

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the previous reviews unless it is requested otherwise._**

------

2023-09-05 19:06 UTC, Meltrust commented on src/App.js
> +function App() {
- [ ]  Please, kindly refactor this and all other functions in your project to ES6 arrow functions, so your code complies with the latest standards.

Refactoring is easy:

```javascript
const App = () => {
  // ...
}
```

## Explanation

The `function` keyword has been soft deprecated in almost all the software industry in favor of ES6 arrow functions. This means, almost nobody uses it anymore, so much that it's considered a non-best practice.

You can do a search in Vscode for the "function" word, and correct as needed.  Shouldn't take you more than 5-10 min so don't worry (I found only 4):

![image](https://github.com/Bennyjoez/motorcycle-appointment-app-front-end/assets/57421823/83f697c1-a39b-44db-95ee-4d3d5c49cec4)


That way, your code will meet the latest standards. 💪

2023-09-06 07:20 UTC, Meltrust approved these changes
#### Hi @Adams-Ghub,


# **Wow, you did it 🎉**
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for the changes implemented 💪 🥇 ㊗️ 
#### _Unless you want to add more features, go ahead to your final presentation ⏩ ⏩ ⏩_ 
## You are about to finish the Microverse program.  You have come a long way!!!




### Good luck in the software industry!!  I'll see you there. ✨
### **Congratulations!!!!!!**  🎉
![applause](https://media.giphy.com/media/srg19CG0cKMuI/giphy.gif)




Cheers and Happy coding!👏👏👏


------

2023-09-06 07:30 UTC, Bennyjoez commented
Thank you very much @Meltrust We sure are happy 😄 🕺🏾 👯 @Adams-Ghub @Mikey1-nuel @harshi0102 Bravoo 👏🏾 👏🏾

2023-09-06 08:52 UTC, merged